config/routes.rb
Flowfeeds::Application.routes.draw do
  devise_for :admins
  devise_for :users, controllers: { sessions: 'sessions' }, skip: [:sessions]
  devise_scope :user do
    post '/sessions'   => 'sessions#create'
    delete '/sessions' => 'sessions#destroy'
  end

  concern :has_many_tracks do
    resources :tracks, only: [:index]
  end

  resources :feeds, only: [:index, :show], concerns: :has_many_tracks do
    member do
      post 'played'
    end
  end

  resources :genres, only: [:index], concerns: :has_many_tracks do
    resources :feeds,  only: [:index]
    member do
      post 'played'
    end
  end
  resources :listens, only: [:create]
  resources :plays, only: [:create]
  resources :playlists, only: [:index, :create, :destroy] do
    resources :playlist_items, only: [:index] do
      collection do
        post :order
      end
    end
    member do
      post :add
      post :remove
    end
  end
  resources :playlist_items, only: [:destroy]

  resources :tracks, only: [:index, :show] do
    collection do
      get :unplayed_count
    end
  end
  resources :videos, only: [:index]
  resources :watches, only: [:create]
  resources :registrations, only: [:create]

  namespace :admin do
    resources :artists do
      collection do
        get 'autocomplete'
      end
    end
    resources :feeds do
      member do
        post :enqueue_updater
      end
    end
    resources :tracks
    resources :videos
    authenticate :admin do
      mount Resque::Server, at: 'resque'
    end
    root to: 'welcome#index'
  end

  namespace :api do
    resources :videos, only: [:create]
  end

  root to: 'welcome#index'
end

app/models/artist.rb
class Artist < ActiveRecord::Base
  has_many :feeds
  has_many :playables

  def videos
    playables.where(type: Video.to_s)
  end
end

app/controllers/admin/artists_controller.rb
class Admin::ArtistsController < AdminController
  before_filter :authenticate_admin!

  def index
    @artists = Artist.all
  end

  def autocomplete
    @artists = Artist.where("name like ?", "%#{params[:q]}%")

    render json: @artists
  end

  def show
    @artist = Artist.find(params[:id])
  end

  def new
    @artist = Artist.new
  end

  def create
    @artist = Artist.new(artist_params)

    if @artist.save
      redirect_to admin_artist_path(@artist), notice: "Updated artist"
    else
      render :new
    end
  end

  def edit
    @artist = Artist.find(params[:id])
  end

  def update
    @artist = Artist.find(params[:id])

    if @artist.update_attributes(artist_params)
      redirect_to admin_artist_path(@artist), notice: "Updated artist"
    else
      render :edit
    end
  end

  def destroy
    @artist = Artist.find(params[:id])
    @artist.destroy

    redirect_to admin_artists_path, notice: "Poor lil guy :("
  end

  protected

  def artist_params
    params.require(:artist).permit(:name)
  end
end

app/views/admin/artists/_form.html.erb
<%= form_for([:admin, @artist], html: { class: "form-horizontal" }) do |f| %>
  <% if @artist.errors.any? %>
    <div class="alert alert-error">
      <ul class="unstyled">
      <% @artist.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :name, class: 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, class: 'input-xxlarge'  %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/admin/artists/edit.html.erb
<%= render 'form' %>

app/views/admin/artists/index.html.erb
<div class="page-header">
  <div class="pull-right">
    <%= link_to "Create artist", new_admin_artist_path, class: 'btn' %>
  </div>
  <h1>Artists</h1>
</div>

<table class="table">
  <tbody>
  <% @artists.each do |artist| %>
    <tr>
      <td><%= artist.id %></td>
      <td><%= link_to artist.name, admin_artist_path(artist) %></td>
      <td><%= link_to "edit", edit_admin_artist_path(artist) %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/admin/artists/new.html.erb
<%= render 'form' %>

app/views/admin/artists/show.html.erb
<div class="page-header">
  <div class="pull-right">
    <%= link_to "Edit", edit_admin_artist_path(@artist), class: 'btn' %>
    <%= link_to "Destroy", admin_artist_path(@artist), method: :delete, confirm: "Are you sure?", class: 'btn btn-danger' %>
  </div>
  <h1><%= @artist.name %></h1>
</div>

<% if @artist.feeds.any? %>
  <h2>Feeds</h2>
  <table class="table">
    <tbody>
    <% @artist.feeds.each do |feed| %>
      <tr>
        <td><%= link_to feed.title, admin_feed_path(feed) %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
<% end%>

<% if @artist.videos.any? %>
  <h2>Videos</h2>
  <table class="table">
    <tbody>
    <% @artist.videos.each do |video| %>
      <tr>
        <td><%= image_tag video.thumb, style: "height: 90px; width: 120px" %></td>
        <td><%= link_to video.title, admin_video_path(video) %></td>
        <td><%= l(video.published) %></td>
        <td><%= link_to "edit", edit_admin_video_path(video) %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
<% end %>