config/routes.rb
Flowfeeds::Application.routes.draw do
  devise_for :admins
  devise_for :users, controllers: { sessions: 'sessions' }, skip: [:sessions]
  devise_scope :user do
    post '/sessions'   => 'sessions#create'
    delete '/sessions' => 'sessions#destroy'
  end

  concern :has_many_tracks do
    resources :tracks, only: [:index]
  end

  resources :feeds, only: [:index, :show], concerns: :has_many_tracks do
    member do
      post 'played'
    end
  end

  resources :genres, only: [:index], concerns: :has_many_tracks do
    resources :feeds,  only: [:index]
    member do
      post 'played'
    end
  end
  resources :listens, only: [:create]
  resources :plays, only: [:create]
  resources :playlists, only: [:index, :create, :destroy] do
    resources :playlist_items, only: [:index] do
      collection do
        post :order
      end
    end
    member do
      post :add
      post :remove
    end
  end
  resources :playlist_items, only: [:destroy]

  resources :tracks, only: [:index, :show] do
    collection do
      get :unplayed_count
    end
  end
  resources :videos, only: [:index]
  resources :watches, only: [:create]
  resources :registrations, only: [:create]

  namespace :admin do
    resources :artists do
      collection do
        get 'autocomplete'
      end
    end
    resources :feeds do
      member do
        post :enqueue_updater
      end
    end
    resources :tracks
    resources :videos
    authenticate :admin do
      mount Resque::Server, at: 'resque'
    end
    root to: 'welcome#index'
  end

  namespace :api do
    resources :videos, only: [:create]
  end

  root to: 'welcome#index'
end

app/models/feed.rb
require "#{Rails.root}/lib/remote_file"

class Feed < ActiveRecord::Base
  belongs_to :genre
  belongs_to :artist
  has_many :playables, dependent: :destroy
  validates :url, presence: true, uniqueness: true

  mount_uploader :image, ImageUploader

  after_update :change_playable_artists_if_artist_changed

  def self.user_unplayed(user)
    select("feeds.*, sum((plays.playable_id is null)::integer) as unplayed").
      joins("JOIN playables on (feeds.id = playables.feed_id and playables.hidden = 'f')").
      joins("LEFT OUTER JOIN plays on (plays.user_id = #{user.id.to_i} and playables.id = plays.playable_id)").
      group("feeds.id").
      order("feeds.title")
  end

  def mark_as_played(user)
    tracks.each do |track|
      Play.track(track.id, user)
    end
  end

  def unplayed
    attributes.fetch('unplayed', nil)
  end

  def update_from_feedzirra(fz)
    self.description = fz.description if description.blank?
    self.title       = fz.title if title.blank?
    self.website     = fz.url if website.blank?

    if artist.blank?
      if fz.respond_to?(:itunes_author)
        artist_name = fz.itunes_author
        self.artist = Artist.where(name: artist_name).first_or_create
      end
    end

    if image.blank?
      if fz.respond_to?(:itunes_image) && RemoteFile.exists?(fz.itunes_image)
        self.remote_image_url = fz.itunes_image
      end
    end

    save!
  end

  def add_entry(entry)
    guid = entry.guid || entry.enclosure_url
    return if playables.where(guid: guid).exists?
    return unless RemoteFile.exists?(entry.enclosure_url)

    Track.create do |track|
      track.feed = self
      track.guid = guid
      track.title = entry.title
      track.description = entry.summary
      track.published = entry.published
      track.url = entry.enclosure_url
      track.artist = artist
    end
  end

  def artist_name
    artist.try(:name)
  end

  def artist_name=(name)
    self.artist = Artist.where(name: name).first_or_create
  end

  def change_playable_artists_if_artist_changed
    if artist_id_changed?
      self.playables.update_all(artist_id: artist_id)
    end
  end

end

app/controllers/admin/feeds_controller.rb
class Admin::FeedsController < AdminController
  before_filter :authenticate_admin!

  def index
    @feeds = Feed.all
  end

  def show
    @feed = Feed.find(params[:id])
  end

  def new
    @feed = Feed.new
  end

  def create
    @feed = Feed.new(feed_params)

    if @feed.save
      redirect_to admin_feed_path(@feed), notice: "Updated feed"
    else
      render :new
    end
  end

  def edit
    @feed = Feed.find(params[:id])
  end

  def update
    @feed = Feed.find(params[:id])

    if @feed.update_attributes(feed_params)
      redirect_to admin_feed_path(@feed), notice: "Updated feed"
    else
      render :edit
    end
  end

  def destroy
    @feed = Feed.find(params[:id])
    @feed.destroy

    redirect_to admin_feeds_path, notice: "Poor lil guy :("
  end

  def enqueue_updater
    Resque.enqueue(FeedUpdater, params[:id])
  end

  protected

  def feed_params
    params.require(:feed).permit(
      :artist_id,
      :artist_name,
      :description,
      :genre_id,
      :image,
      :title,
      :url,
      :website
    )
  end
end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  respond_to :json

  def index
    if current_user
      feeds = Genre.find(params[:genre_id]).feeds.user_unplayed(current_user)
    else
      feeds = Genre.find(params[:genre_id]).feeds.order(:title)
    end

    respond_with feeds
  end

  def show
    if current_user
      feed = Feed.user_unplayed(current_user).where(id: params[:id]).first
    else
      feed = Feed.find(params[:id])
    end

    respond_with feed
  end

  def played
    Feed.find(params[:id]).mark_as_played(current_user)

    render json: :ok
  end
end

app/views/admin/feeds/_form.html.erb
<%= form_for([:admin, @feed], html: { class: "form-horizontal" }) do |f| %>
  <% if @feed.errors.any? %>
    <div class="alert alert-error">
      <ul class="unstyled">
      <% @feed.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :title, class: 'control-label' %>
    <div class="controls">
      <%= f.text_field :title, class: 'input-xxlarge'  %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :url, class: 'control-label' %>
    <div class="controls">
      <%= f.text_field :url, class: 'input-xxlarge'  %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :image, class: 'control-label' %>
    <div class="controls">
      <%= f.file_field :image %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :genre_id, class: 'control-label' %>
    <div class="controls">
      <%= f.collection_select :genre_id, Genre.all, :id, :name  %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :artist, class: 'control-label' %>
    <div class="controls">
      <%= f.text_field :artist_name, class: 'input-xxlarge', data: { autocomplete_source: autocomplete_admin_artists_path }  %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :website, class: 'control-label' %>
    <div class="controls">
      <%= f.text_field :website, class: 'input-xxlarge'  %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :description, class: 'control-label' %>
    <div class="controls">
      <%= f.text_area :description, class: 'input-xxlarge' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/admin/feeds/edit.html.erb
<%= render 'form' %>

app/views/admin/feeds/enqueue_updater.js.erb
alert("Updating feed");

app/views/admin/feeds/index.html.erb
<div class="page-header">
  <div class="pull-right">
    <%= link_to "Create feed", new_admin_feed_path, class: 'btn' %>
  </div>
  <h1>Feeds</h1>
</div>

<table class="table">
  <tbody>
  <% @feeds.each do |feed| %>
    <tr>
      <td><%= feed.id %></td>
      <td><%= image_tag feed.image.thumb, style: "height: 36px; width: 36px" %></td>
      <td><%= link_to feed.title, admin_feed_path(feed) %></td>
      <td>
        <% if feed.artist.present? %>
          <%= link_to feed.artist.name, admin_artist_path(feed.artist) %>
        <% end %>
      </td>
      <td><%= link_to "edit", edit_admin_feed_path(feed) %></td>
      <td><%= link_to "update", enqueue_updater_admin_feed_path(feed), remote: true, method: :post %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/admin/feeds/new.html.erb
<%= render 'form' %>

app/views/admin/feeds/show.html.erb
<div class="page-header">
  <div class="pull-right">
    <%= link_to "Update", enqueue_updater_admin_feed_path(@feed), remote: true, method: :post, class: 'btn' %>
    <%= link_to "Edit", edit_admin_feed_path(@feed), class: 'btn' %>
    <%= link_to "Destroy", admin_feed_path(@feed), method: :delete, confirm: "Are you sure?", class: 'btn btn-danger' %>
  </div>
  <h1><%= @feed.title %></h1>
</div>


<div class="row">
  <div class="span4">
    <%= image_tag @feed.image %>
  </div>
  <div class="span8">
    <%= simple_format @feed.description %>
  </div>
</div>

<div class="row">
  <div class="span12">
    <table class="table">
      <tbody>
      <% @feed.playables.each do |track| %>
      <tr>
        <td><%= track.id %></td>
        <td><%= link_to track.title, admin_track_path(track) %></td>
        <td><%= track.hidden %></td>
        <td><%= track.promoted %></td>
        <td><%= link_to 'edit', edit_admin_track_path(track) %></td>
      </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>