config/routes.rb
Flowfeeds::Application.routes.draw do
  devise_for :admins
  devise_for :users, controllers: { sessions: 'sessions' }, skip: [:sessions]
  devise_scope :user do
    post '/sessions'   => 'sessions#create'
    delete '/sessions' => 'sessions#destroy'
  end

  concern :has_many_tracks do
    resources :tracks, only: [:index]
  end

  resources :feeds, only: [:index, :show], concerns: :has_many_tracks do
    member do
      post 'played'
    end
  end

  resources :genres, only: [:index], concerns: :has_many_tracks do
    resources :feeds,  only: [:index]
    member do
      post 'played'
    end
  end
  resources :listens, only: [:create]
  resources :plays, only: [:create]
  resources :playlists, only: [:index, :create, :destroy] do
    resources :playlist_items, only: [:index] do
      collection do
        post :order
      end
    end
    member do
      post :add
      post :remove
    end
  end
  resources :playlist_items, only: [:destroy]

  resources :tracks, only: [:index, :show] do
    collection do
      get :unplayed_count
    end
  end
  resources :videos, only: [:index]
  resources :watches, only: [:create]
  resources :registrations, only: [:create]

  namespace :admin do
    resources :artists do
      collection do
        get 'autocomplete'
      end
    end
    resources :feeds do
      member do
        post :enqueue_updater
      end
    end
    resources :tracks
    resources :videos
    authenticate :admin do
      mount Resque::Server, at: 'resque'
    end
    root to: 'welcome#index'
  end

  namespace :api do
    resources :videos, only: [:create]
  end

  root to: 'welcome#index'
end

app/models/video.rb
class Video < Playable
  before_create :set_published

  def set_published
    last_published = Video.order('published desc').first.published

    if last_published.nil? || last_published <= Time.zone.now
      published = Time.zone.now
    else
      published = last_published + 1.day
    end

    self.published = published
  end

  def thumb
    "http://img.youtube.com/vi/#{youtube_id}/1.jpg"
  end

  def artist_name
    artist.try(:name)
  end

  def artist_name=(name)
    self.artist = Artist.where(name: name).first_or_create
  end

  def youtube_id=(id)
    self.guid = id
  end

  def youtube_id
    guid
  end
end

app/controllers/admin/videos_controller.rb
class Admin::VideosController < AdminController
  before_filter :authenticate_admin!
  skip_before_filter :verify_authenticity_token

  def index
    @videos = Video.order('published desc').all
  end

  def autocomplete
    @videos = Video.where("name like ?", "%#{params[:q]}%")

    render json: @videos
  end

  def show
    @video = Video.find(params[:id])
  end

  def new
    @video = Video.new
  end

  def create
    @video = Video.new(video_params)

    if @video.save
      redirect_to admin_video_path(@video), notice: "Updated video"
    else
      render :new
    end
  end

  def edit
    @video = Video.find(params[:id])
  end

  def update
    @video = Video.find(params[:id])

    if @video.update_attributes(video_params)
      redirect_to admin_video_path(@video), notice: "Updated video"
    else
      render :edit
    end
  end

  def destroy
    @video = Video.find(params[:id])
    @video.destroy

    redirect_to admin_videos_path, notice: "Poor lil guy :("
  end

  protected

  def video_params
    params.require(:video).permit(:title, :youtube_id, :artist_name, :published)
  end
end

app/controllers/api/videos_controller.rb
class Api::VideosController < ApplicationController
  before_filter :authenticate_admin!
  skip_before_filter :verify_authenticity_token

  def create
    video = Video.new(video_params)
    video.save!

    render json: video
  end

  protected

  def video_params
    params.require(:video).permit(:title, :youtube_id, :artist_name)
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  respond_to :json

  def index
    videos = video.public.paginate(page)

    respond_with videos, meta: { total: total, unplayed: unplayed, page: page }
  end

  protected

  def total
    Video.public.count
  end

  def unplayed
    if current_user
      Video.unplayed_count(current_user)
    else
      nil
    end
  end

  def video
    if current_user
      Video.user_played(current_user)
    else
      Video
    end
  end
end

app/views/admin/videos/_form.html.erb
<%= form_for([:admin, @video], html: { class: "form-horizontal" }) do |f| %>
  <% if @video.errors.any? %>
    <div class="alert alert-error">
      <ul class="unstyled">
      <% @video.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :title, class: 'control-label' %>
    <div class="controls">
      <%= f.text_field :title, class: 'input-xxlarge'  %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :youtube_id, class: 'control-label' %>
    <div class="controls">
      <%= f.text_field :youtube_id, class: 'input-xxlarge'  %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :artist, class: 'control-label' %>
    <div class="controls">
      <%= f.text_field :artist_name, class: 'input-xxlarge', data: { autocomplete_source: autocomplete_admin_artists_path }  %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :published, class: 'control-label' %>
    <div class="controls">
      <%= f.datetime_select :published %>
    </div>
  </div>


  <div class="form-actions">
    <%= f.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/admin/videos/edit.html.erb
<%= render 'form' %>

app/views/admin/videos/index.html.erb
<div class="page-header">
  <div class="pull-right">
    <%= link_to "Create video", new_admin_video_path, class: 'btn' %>
  </div>
  <h1>Videos</h1>
</div>

<table class="table">
  <tbody>
  <% @videos.each do |video| %>
    <tr>
      <td><%= video.id %></td>
      <td><%= image_tag video.thumb, style: "height: 90px; width: 120px" %></td>
      <td>
        <div> <%= link_to video.title, admin_video_path(video) %> </div>
        <% if video.artist.present? %>
          <%= link_to video.artist.name, admin_artist_path(video.artist) %>
        <% end %>
      </td>
      <td><%= l(video.published, format: :long) %></td>
      <td><%= video.youtube_id %></td>
      <td><%= link_to "edit", edit_admin_video_path(video) %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/admin/videos/new.html.erb
<%= render 'form' %>

app/views/admin/videos/show.html.erb
<div class="page-header">
  <div class="pull-right">
    <%= link_to "Edit", edit_admin_video_path(@video), class: 'btn' %>
    <%= link_to "Destroy", admin_video_path(@video), method: :delete, confirm: "Are you sure?", class: 'btn btn-danger' %>
  </div>
  <h1><%= @video.title %></h1>
</div>

<%= image_tag @video.thumb %>