config/routes.rb
Flowfeeds::Application.routes.draw do
  devise_for :admins
  devise_for :users, controllers: { sessions: 'sessions' }, skip: [:sessions]
  devise_scope :user do
    post '/sessions'   => 'sessions#create'
    delete '/sessions' => 'sessions#destroy'
  end

  concern :has_many_tracks do
    resources :tracks, only: [:index]
  end

  resources :feeds, only: [:index, :show], concerns: :has_many_tracks do
    member do
      post 'played'
    end
  end

  resources :genres, only: [:index], concerns: :has_many_tracks do
    resources :feeds,  only: [:index]
    member do
      post 'played'
    end
  end
  resources :listens, only: [:create]
  resources :plays, only: [:create]
  resources :playlists, only: [:index, :create, :destroy] do
    resources :playlist_items, only: [:index] do
      collection do
        post :order
      end
    end
    member do
      post :add
      post :remove
    end
  end
  resources :playlist_items, only: [:destroy]

  resources :tracks, only: [:index, :show] do
    collection do
      get :unplayed_count
    end
  end
  resources :videos, only: [:index]
  resources :watches, only: [:create]
  resources :registrations, only: [:create]

  namespace :admin do
    resources :artists do
      collection do
        get 'autocomplete'
      end
    end
    resources :feeds do
      member do
        post :enqueue_updater
      end
    end
    resources :tracks
    resources :videos
    authenticate :admin do
      mount Resque::Server, at: 'resque'
    end
    root to: 'welcome#index'
  end

  namespace :api do
    resources :videos, only: [:create]
  end

  root to: 'welcome#index'
end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Flowfeeds</title>
  <%= stylesheet_link_tag "admin", media: "all" %>
  <%= javascript_include_tag "admin" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container" style="padding-top: 20px">

  <div class="navbar">
    <div class="navbar-inner">
      <a class="brand" href="#">Flowfeeds Admin</a>
      <ul class="nav">
        <li><%= link_to "Artists", admin_artists_path %></li>
        <li><%= link_to "Feeds", admin_feeds_path %></li>
        <li><%= link_to "Videos", admin_videos_path %></li>
        <li><%= link_to "Resque", admin_resque_server_path %></li>
      </ul>
      <ul class="nav pull-right">
        <li><%= link_to "Sign out", destroy_admin_session_path, method: :delete %></li>
      </ul>
    </div>
  </div>

  <%= yield %>

</div>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Flowfeeds</title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= yield %>
  <%= javascript_tag do %>
    <% if current_user %>
      window.current_user = <%= UserSerializer.new(current_user, root: false).to_json.html_safe %>;
      window.unplayed_video_count = <%= Video.unplayed_count(current_user).to_json.html_safe %>;
      window.genres = <%= Genre.user_unplayed(current_user).to_json.html_safe %>;
      window.playlists = <%= current_user.playlists.to_json(only: [:id, :name]).html_safe %>;
    <% else %>
      window.genres = <%= Genre.all.to_json.html_safe %>;
    <% end %>
  <% end %>
  <%= render 'ga' %>
  <%= javascript_include_tag "vendor" %>
  <%= javascript_include_tag "application" %>
</body>
</html>